# jobs:
#   include:
#     - script: echo "Running chapter tests"
#     - stage: Test
#       # Create all the main.tex test files, and run the docker command.
#       script:
#         - ./tests/scripts/test "rrtfunnel"
#     # We will use the docker image from https://hub.docker.com/r/strauman/travis-latexbuild/
#     # script:
#     # - docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small
#   # - # stage name not required, will continue to use `test`
#   #   script: ./test 2
#   # - # stage name not required, will continue to use `test`
#   #   script: ./test 2
#   # - # stage name not required, will continue to use `test`
#   #   script: ./test 2
#   # - # stage name not required, will continue to use `test`
#   #   script: ./test 2
#   # - # stage name not required, will continue to use `test`
#   #   script: ./test 2
#   # - stage: GitHub Release
#   #   script: echo "Deploying to GitHub releases ..."
#   #   deploy:
#   #     provider: releases
#   #     api_key: $GITHUB_OAUTH_TOKEN
#   #     skip_cleanup: true
#   #     on:
#   #       tags: true
dist: xenial

sudo: required

language: generic


# Safelist - Only build the master branch.
# branches:
#   only:
#     - master

# file:
#   - ./src/main.pdf
#   ./otherfile.pdf# #
#   skip_cleanup: true
#   on:
#     tags: true
#     branch: master

# Dependency of the minted package
before_install:
  - sudo apt-get install python-pygments

install:
  - source ./texlive/texlive_install.sh

# cache:
#   directories:
#     - /tmp/texlive
#     - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/src/

jobs:
  include:
    - stage: Test
      # Create all the main.tex test files, and run the docker command.
      script:
        # - ./tests/scripts/test "rrtfunnel"
        - echo $(pwd)
        - texliveonfly -shell-escape ./main.tex
# script:
# # texliveonfly will download packages automatically, running pdflatex by default. Change compiler with e.g. --compiler=lualatex
# - texliveonfly -shell-escape ./src/main.tex
# # Compile twice to fix possible references
# - texliveonfly -shell-escape ./src/main.tex
