* Date today
**  Every sub-level-set of a funnel is also a funnel! This means that starting out in a sub-level-set, you are guaranteed to remain the sub-level-set, due to the nature of Lyapunov functions!
**  Create SOS Chapter based on edX lectures in underactuated robotics with Russ Tedrake. Especially the funnel lecture! (Do cite this also!)
**  Collision-checking for funnels can be done using a convex-quadratic-program ( for quadratic Lyapunov functions that is!).
**  As every sub-level set of a funnel is also a funnel, the funnels can be trimmed down in case of a collision!
   
* 5/3/19
** Start the Experiments section
*** FIXED Deciding on vehicle and obstacle relative sizes and measuremeants and scaling (Have it all in m?) How big is a tree?
    CLOSED: [2019-03-05 Tue 14:59]
**** Should this go in the method section also? 
*** FIXED Moving the funnel expansion part here (First decide on the size of the vehicle.)
    CLOSED: [2019-03-05 Tue 14:59]
*** FIXED Write the poisson tree generation part.
    CLOSED: [2019-03-05 Tue 14:59]
*** DONE Create the benchmark RRT-planner which optimizes the distance to the nearest obstacle in the Euclidean metric.
    CLOSED: [2019-03-05 Tue 10:41]
    - State "DONE"       from "PR"         [2019-03-05 Tue 10:41]
**** Currently no max distance to obstacles. 
     - State "DONE"       from "MERGED"     [2019-03-05 Tue 16:02]
** General
*** FIXED Organize the intro section properly. Move some funnel parts to the first appendix.
    CLOSED: [2019-03-06 Wed 09:01]
*  6/3/19
** Write RRT-Intro part.
*** FIXED Need to find more sources to build this on. What is to be included in it?
    CLOSED: [2019-03-06 Wed 13:19]
**** Find literature on general rrt's. Master and doctoral thesis' probably a good place to start.
*** FIXED Write the RRT motion primitves section in the introduction.
    CLOSED: [2019-03-06 Wed 16:28]
**  Experiments
*** FIXED What more to do with the benchmark planner?
    CLOSED: [2019-03-06 Wed 18:57]
****  Is it necessary to have max-dist to obstacles? Why not leave it as is?
*** FIXED Add wheels to the vehicle visualizer. 
    CLOSED: [2019-03-06 Wed 18:41]
** FIXED General
   CLOSED: [2019-03-06 Wed 13:21]
*** FIXED Cleanup all the double references from multiple zot and bib files (What a mess!).
*** FIXED Fixup the dead cite keys in all chapters.
*** FIXED Even after the duplicate bib files are merged, I get duplicate entries. Why?
    CLOSED: [2019-03-06 Wed 09:52]
 
* 7/3/19
** Experiments
*** FIXED [#A] The motion primitives themselves must be able to be broken down into sub-motion-primitives.
    CLOSED: [2019-03-07 Thu 13:37]
*** FIXED The optimization problems needs to be cleaned up!
    CLOSED: [2019-03-07 Thu 15:16]

* 13/3/19
** General
*** Maybe base the general introduction on  http://msl.cs.uiuc.edu/~pcheng1/papers/thesis.pdf (p15-16)
*** Some ISBN's in the bibliography are dead. Have a look at this.
*** Have a look at the essay, and figure out what has to be done with it before the final submission.
*** Have a look at this repo and code: https://web.stanford.edu/~ssingh19/software.html
**  Write RRT-Intro part.
*** [#B] Cleanup the RRT-motion primitives section.
*** [#B] Continue writing the RRT-Intro. 
*** [Rejected] Start adding sub-funnels as motion primitives to the RRT-Funnel algorithm!
    - State "DONE"       from "MERGED"     [2019-03-13 Wed 13:03]
**** The cutBeginning funtions are not working correctly. Why?
** General
*** FIXED [#B] Add a nice picture showing the size of the vehicle used in the experiments, to the determine the size section.
    CLOSED: [2019-03-13 Wed 17:08]
**** The general size of the funels must be expanded prior to storage. That would probably be easiest!.
***  Uniform sampling in SO(2), add and how to?.
***  Add more motion primitives (Long, medium and short ones).
***  Make sure that only composable funnels are composed together.
** Experiments
*** [Rejected] Fixup the bugz in the subfunnel algorithm part.
*** Add a datastructure for checking which funnels are composable and not.
** Method
*** [#B] Add the RRT-Funnel motion primitive algorithm design to the method section.
*** [#C] Need literature on RRT with motion primitives -> Find more!
***  Change the create funnel graph algorithm to only check at the ends. No sub-times.
****  ~\cite{vonasekGlobalMotionPlanning2013}
****  \cite{vonasekHighlevelMotionPlanning2015}
*** Write the RRT distance metric section in the method chapter.
