#!/bin/bash
# Create the correct include only from the main.tex file in /src.

if [ $# -ne 2 ]; then
    echo "Usage:\n - createIncludeOnly 'section-name' 'path/to/main.tex'"
    exit 1
fi

awk -f tests/scripts/awkscript section_name="$1" $2 > tmp.tex
mv tmp.tex tests/$1/main.tex
rm tmp.tex

exit 0


