#!/bin/bash
# Test script employed by travis to run the tests for each section
# of the thesis.

for dir in $(ls tests); do
    if [ $dir == "scripts" ]; then
        continue
    fi
    # get the name of the tests/subdirectory and only create the
    # main.tex file for this subdir.
    if [ $dir == tests/$1 ]; then
        tests/scripts/createIncludeOnly "$dir" 'src/main.tex'
    fi
done

# We will use the docker image from https://hub.docker.com/r/strauman/travis-latexbuild/
# Now that all the main.tex test files have been created,
# run all the tests from tex-config.build-pattern.
docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small

